# Generated by Django 3.1.2 on 2020-10-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('language', models.IntegerField(choices=[(1, 'Português'), (2, 'Ingles')])),
                ('location', models.CharField(default='Url', max_length=100)),
                ('InteractivityType', models.IntegerField(choices=[(1, 'Animação'), (1, 'Rolagem de barra'), (1, 'Inserir número')])),
                ('context', models.IntegerField(choices=[(1, 'Geometria'), (2, 'Cálculo'), (3, 'Estatística'), (4, 'Aritimética'), (5, 'Trigonometria'), (6, 'Álgebra'), (7, 'Probabilidade'), (8, 'Funções')])),
                ('copyright', models.CharField(default='Autor', max_length=50)),
            ],
        ),
    ]
