# Generated by Django 3.1.2 on 2020-11-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(default='1', max_length=100)),
                ('language', models.CharField(choices=[('PT', 'Português'), ('EN', 'Ingles')], default='PT', max_length=20)),
                ('location', models.CharField(default='Url', max_length=100)),
                ('interactivity', models.CharField(choices=[('Animação', 'Animação'), ('BarRolling', 'BarRolling'), ('Number', 'Inserir número')], default='1', max_length=20)),
                ('context', models.CharField(choices=[('Geometria', 'Geometria'), ('Cálculo', 'Cálculo'), ('Estatística', 'Estatística'), ('Aritimética', 'Aritimética'), ('Trigonometria', 'Trigonometria'), ('Álgebra', 'Álgebra'), ('Probabilidade', 'Probabilidade'), ('Funções', 'Funções')], default='1', max_length=20)),
                ('copyright', models.CharField(default='Autor', max_length=50)),
            ],
        ),
    ]
